 ### Note:
    This encoding technique technique is applied where tyou have higher number of categories.
    This technique basically replace each label of categorical variable by the count
 ### Advantanges
     It is simple to implement
     It does not inccrease the feature dimensional space
 
 ### Disadvantages
      If the some of the lableshas same count , then we will replace with the same count and it will losesome valuable information

In [3]:
import pandas as pd 
import numpy as np
df = pd.read_csv('train.csv')

In [30]:
df.head()

   ID       y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X374  X375  X376  X377  X378  X379  X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     0     1     0     0     0     0     0     0     0
1   6   88.53   k  t  av  e  d  y  l  o    0  ...     0     1     0     0     0     0     0     0     0     0     0
2   7   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0     0     0     1     0     0     0
3   9   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0     0     0     0     0     0     0
4  13   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0     0     0     0     0     0     0

[5 rows x 378 columns]

In [6]:
df1 = pd.read_csv('train.csv' , usecols=['X1','X2'])

In [7]:
df1.head()

  X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [18]:
df1['X1'].value_counts()

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
f      23
y      23
j      22
n      19
k      17
p       9
g       6
q       3
d       3
ab      3
Name: X1, dtype: int64

In [19]:
df1['X1'].unique()

array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
       'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
       'ab'], dtype=object)

In [20]:
df1['X2'].unique()

array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
       'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
       'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
       'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object)

In [21]:
print(len(df1['X1'].unique()))
print(len(df1['X2'].unique()))

27
44

In [22]:
for col in df1.columns[0:]:
    print(col ,":",len(df1[col].unique()),"labels")

X1 : 27 labels
X2 : 44 labels

In [24]:
df1['X2'].value_counts().to_dict()

{'as': 1659,
 'ae': 496,
 'ai': 415,
 'm': 367,
 'ak': 265,
 'r': 153,
 'n': 137,
 's': 94,
 'f': 87,
 'e': 81,
 'aq': 63,
 'ay': 54,
 'a': 47,
 't': 29,
 'i': 25,
 'k': 25,
 'b': 21,
 'ao': 20,
 'z': 19,
 'ag': 19,
 'd': 18,
 'ac': 13,
 'g': 12,
 'ap': 11,
 'y': 11,
 'x': 10,
 'aw': 8,
 'at': 6,
 'h': 6,
 'q': 5,
 'an': 5,
 'al': 5,
 'ah': 4,
 'av': 4,
 'p': 4,
 'au': 3,
 'o': 1,
 'c': 1,
 'am': 1,
 'ar': 1,
 'l': 1,
 'j': 1,
 'af': 1,
 'aa': 1}

In [25]:
frequency = df1['X2'].value_counts().to_dict()

In [26]:
df1['X2'] = df1['X2'].map(frequency)

In [27]:
df1.head()

  X1   X2
0  v    6
1  t    4
2  w  137
3  t  137
4  v  137

In [29]:
# We can apply for X1 as well